// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"architecture-lab-3/server/virtual-machines"
)

// Injectors from modules.go:

func ComposeApiServer(port HttpPortNumber) (*APIServer, error) {
	db, err := NewDbConnection()
	if err != nil {
		return nil, err
	}
	store := virtualmachines.NewStore(db)
	httpHandlerFunc := virtualmachines.HttpHandler(store)
	apiServer := &APIServer{
		Port:      port,
		vmHandler: httpHandlerFunc,
	}
	return apiServer, nil
}
